language: cpp

sudo: true

compiler:
  - gcc
# - clang

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - ./travis-dependencies.sh

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_script:
  - mkdir build
  - cd build

script:
  - cmake ../
  - make
  - ./agsgd_test
